# Generated by Django 5.1.7 on 2025-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0006_merge_20250521_1428"),
        ("users", "0002_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Your favorite food categories",
                related_name="favorited_by",
                to="food.category",
            ),
        ),
    ]
