# Generated by Django 5.1.7 on 2025-05-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0006_merge_20250521_1428"),
        ("users", "0003_profile_favorites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="favorites",
        ),
        migrations.AddField(
            model_name="profile",
            name="favorite",
            field=models.ForeignKey(
                blank=True,
                help_text="Your single favorite food category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorited_by_users",
                to="food.category",
            ),
        ),
    ]
